name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Select release version
        id: version
        run: printf 'version=1.%(%Y%m%d.%H%M)T' >> $GITHUB_OUTPUT

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Publish
        run: |
          echo 'Setting version ${{ steps.version.outputs.version }} in package descriptor'
          sed -i -e 's|0.0.0|${{ steps.version.outputs.version }}|g' package.json
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm install
          npm publish --access public
          rm -f ~/.npmrc

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: robobays
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=registry,ref=robobays/replay-timeline:buildcache
          cache-to: type=registry,ref=robobays/replay-timeline:buildcache,mode=max
          platforms: linux/amd64
          push: true
          tags: robobays/replay-timeline:latest
